all:
	g++ -o write write.cpp address_book.pb.cc -I/usr/local/include -L/usr/local/lib -lprotobuf -lpthread
	g++ -o write_v2 write_v2.cpp address_book_v2.pb.cc -I/usr/local/include -L/usr/local/lib -lprotobuf -lpthread
	g++ -o read read.cpp address_book.pb.cc -I/usr/local/include -L/usr/local/lib -lprotobuf -lpthread
	g++ -o read_v2 read_v2.cpp address_book_v2.pb.cc -I/usr/local/include -L/usr/local/lib -lprotobuf -lpthread
