all:
	g++ -o write write.cpp address_book.pb.cc -I/usr/local/include -L/usr/local/lib -lprotobuf -lpthread
	g++ -o read read.cpp address_book.pb.cc -I/usr/local/include -L/usr/local/lib -lprotobuf -lpthread
